/**
 * Standard Component Definitions and Pin Layouts
 */

import { ComponentDefinition, GateType } from '../types/circuit';

export const COMPONENT_DEFINITIONS: Record<GateType, ComponentDefinition> = {
  AND: {
    type: 'AND',
    name: 'AND Gate',
    category: 'gates',
    description: 'Outputs 1 only when all inputs are 1. (Y = A · B)',
    width: 90,
    height: 60,
    defaultInputs: [
      { name: 'A', label: 'A' },
      { name: 'B', label: 'B' },
    ],
    defaultOutputs: [{ name: 'OUT', label: 'Q' }],
    hasTransistorView: true,
    truthTableSummary: '00->0, 01->0, 10->0, 11->1',
  },
  OR: {
    type: 'OR',
    name: 'OR Gate',
    category: 'gates',
    description: 'Outputs 1 when at least one input is 1. (Y = A + B)',
    width: 90,
    height: 60,
    defaultInputs: [
      { name: 'A', label: 'A' },
      { name: 'B', label: 'B' },
    ],
    defaultOutputs: [{ name: 'OUT', label: 'Q' }],
    hasTransistorView: true,
    truthTableSummary: '00->0, 01->1, 10->1, 11->1',
  },
  NOT: {
    type: 'NOT',
    name: 'NOT Inverter',
    category: 'gates',
    description: 'Inverts the incoming signal. (Y = ¬A)',
    width: 80,
    height: 50,
    defaultInputs: [{ name: 'IN', label: 'A' }],
    defaultOutputs: [{ name: 'OUT', label: 'Q' }],
    hasTransistorView: true,
    truthTableSummary: '0->1, 1->0',
  },
  NAND: {
    type: 'NAND',
    name: 'NAND Gate',
    category: 'gates',
    description: 'Universal gate. Outputs 0 only when both inputs are 1.',
    width: 90,
    height: 60,
    defaultInputs: [
      { name: 'A', label: 'A' },
      { name: 'B', label: 'B' },
    ],
    defaultOutputs: [{ name: 'OUT', label: 'Q' }],
    hasTransistorView: true,
    truthTableSummary: '00->1, 01->1, 10->1, 11->0',
  },
  NOR: {
    type: 'NOR',
    name: 'NOR Gate',
    category: 'gates',
    description: 'Universal gate. Outputs 1 only when both inputs are 0.',
    width: 90,
    height: 60,
    defaultInputs: [
      { name: 'A', label: 'A' },
      { name: 'B', label: 'B' },
    ],
    defaultOutputs: [{ name: 'OUT', label: 'Q' }],
    hasTransistorView: true,
    truthTableSummary: '00->1, 01->0, 10->0, 11->0',
  },
  XOR: {
    type: 'XOR',
    name: 'XOR Gate',
    category: 'gates',
    description: 'Exclusive OR. Outputs 1 when inputs differ. (Y = A ⊕ B)',
    width: 90,
    height: 60,
    defaultInputs: [
      { name: 'A', label: 'A' },
      { name: 'B', label: 'B' },
    ],
    defaultOutputs: [{ name: 'OUT', label: 'Q' }],
    hasTransistorView: true,
    truthTableSummary: '00->0, 01->1, 10->1, 11->0',
  },
  XNOR: {
    type: 'XNOR',
    name: 'XNOR Gate',
    category: 'gates',
    description: 'Equivalence gate. Outputs 1 when inputs match.',
    width: 90,
    height: 60,
    defaultInputs: [
      { name: 'A', label: 'A' },
      { name: 'B', label: 'B' },
    ],
    defaultOutputs: [{ name: 'OUT', label: 'Q' }],
    hasTransistorView: false,
    truthTableSummary: '00->1, 01->0, 10->0, 11->1',
  },
  BUFFER: {
    type: 'BUFFER',
    name: 'Buffer',
    category: 'gates',
    description: 'Passes logic value unchanged with signal regeneration.',
    width: 80,
    height: 50,
    defaultInputs: [{ name: 'IN', label: 'A' }],
    defaultOutputs: [{ name: 'OUT', label: 'Q' }],
    hasTransistorView: false,
  },
  CONST_HIGH: {
    type: 'CONST_HIGH',
    name: 'Constant HIGH (1)',
    category: 'inputs',
    description: 'Fixed 5.0V Logic 1 voltage rail source.',
    width: 50,
    height: 40,
    defaultInputs: [],
    defaultOutputs: [{ name: 'OUT', label: '1' }],
  },
  CONST_LOW: {
    type: 'CONST_LOW',
    name: 'Constant LOW (0)',
    category: 'inputs',
    description: 'Fixed 0.0V Ground (Logic 0) reference.',
    width: 50,
    height: 40,
    defaultInputs: [],
    defaultOutputs: [{ name: 'OUT', label: '0' }],
  },
  SWITCH: {
    type: 'SWITCH',
    name: 'Toggle Switch',
    category: 'inputs',
    description: 'Click or tap to toggle between Logic 0 (0V) and Logic 1 (5V).',
    width: 70,
    height: 50,
    defaultInputs: [],
    defaultOutputs: [{ name: 'OUT', label: 'Q' }],
  },
  BUTTON: {
    type: 'BUTTON',
    name: 'Push Button',
    category: 'inputs',
    description: 'Momentary contact: outputs 1 while pressed, 0 when released.',
    width: 70,
    height: 50,
    defaultInputs: [],
    defaultOutputs: [{ name: 'OUT', label: 'Q' }],
  },
  CLOCK: {
    type: 'CLOCK',
    name: 'Clock Generator',
    category: 'inputs',
    description: 'Generates continuous digital square-wave clock pulses.',
    width: 70,
    height: 50,
    defaultInputs: [],
    defaultOutputs: [{ name: 'CLK', label: 'CLK' }],
  },
  LED: {
    type: 'LED',
    name: 'LED Indicator',
    category: 'outputs',
    description: 'Glows brightly when input is HIGH (5V), off when LOW (0V).',
    width: 50,
    height: 50,
    defaultInputs: [{ name: 'IN', label: 'IN' }],
    defaultOutputs: [],
  },
  PROBE: {
    type: 'PROBE',
    name: 'Logic & Voltage Probe',
    category: 'outputs',
    description: 'Displays precise digital logic state and analog voltage.',
    width: 80,
    height: 50,
    defaultInputs: [{ name: 'IN', label: 'IN' }],
    defaultOutputs: [],
  },
  SEVEN_SEGMENT: {
    type: 'SEVEN_SEGMENT',
    name: '7-Segment Display',
    category: 'outputs',
    description: '7 separate input lines controlling display segments a through g.',
    width: 90,
    height: 120,
    defaultInputs: [
      { name: 'a', label: 'a' },
      { name: 'b', label: 'b' },
      { name: 'c', label: 'c' },
      { name: 'd', label: 'd' },
      { name: 'e', label: 'e' },
      { name: 'f', label: 'f' },
      { name: 'g', label: 'g' },
    ],
    defaultOutputs: [],
  },
  HEX_DISPLAY: {
    type: 'HEX_DISPLAY',
    name: 'Hex Decoder Display',
    category: 'outputs',
    description: '4-bit binary input (D3-D0) rendered as hexadecimal (0-F).',
    width: 90,
    height: 100,
    defaultInputs: [
      { name: 'D3', label: '8' },
      { name: 'D2', label: '4' },
      { name: 'D1', label: '2' },
      { name: 'D0', label: '1' },
    ],
    defaultOutputs: [],
  },
  BUZZER: {
    type: 'BUZZER',
    name: 'Audio Buzzer',
    category: 'outputs',
    description: 'Emits an audible tone when activated by HIGH logic state.',
    width: 60,
    height: 50,
    defaultInputs: [{ name: 'IN', label: 'IN' }],
    defaultOutputs: [],
  },
  TIMING_ANALYZER: {
    type: 'TIMING_ANALYZER',
    name: 'Oscilloscope (Timing Analyzer)',
    category: 'outputs',
    description: 'Multi-channel digital logic oscilloscope. Plots digital square waveforms, voltages, and timing relationships over time.',
    width: 260,
    height: 180,
    defaultInputs: [
      { name: 'CH1', label: 'CH 1' },
      { name: 'CH2', label: 'CH 2' },
      { name: 'CH3', label: 'CH 3' },
      { name: 'CH4', label: 'CH 4' },
    ],
    defaultOutputs: [],
  },
  HALF_ADDER: {
    type: 'HALF_ADDER',
    name: 'Half Adder',
    category: 'arithmetic',
    description: 'Adds two 1-bit binary inputs, outputting Sum and Carry.',
    width: 100,
    height: 70,
    defaultInputs: [
      { name: 'A', label: 'A' },
      { name: 'B', label: 'B' },
    ],
    defaultOutputs: [
      { name: 'SUM', label: 'S' },
      { name: 'CARRY', label: 'C' },
    ],
  },
  FULL_ADDER: {
    type: 'FULL_ADDER',
    name: 'Full Adder',
    category: 'arithmetic',
    description: 'Adds three 1-bit inputs (A, B, Cin) with Sum and Cout.',
    width: 110,
    height: 90,
    defaultInputs: [
      { name: 'A', label: 'A' },
      { name: 'B', label: 'B' },
      { name: 'CIN', label: 'Cin' },
    ],
    defaultOutputs: [
      { name: 'SUM', label: 'S' },
      { name: 'COUT', label: 'Cout' },
    ],
  },
  MUX_2TO1: {
    type: 'MUX_2TO1',
    name: '2:1 Multiplexer',
    category: 'plexers',
    description: 'Selects between inputs I0 and I1 based on selector pin S.',
    width: 100,
    height: 80,
    defaultInputs: [
      { name: 'I0', label: 'I0' },
      { name: 'I1', label: 'I1' },
      { name: 'S', label: 'S' },
    ],
    defaultOutputs: [{ name: 'Y', label: 'Y' }],
  },
  DEMUX_1TO2: {
    type: 'DEMUX_1TO2',
    name: '1:2 Demultiplexer',
    category: 'plexers',
    description: 'Routes data input IN to either Y0 or Y1 based on selector S.',
    width: 100,
    height: 80,
    defaultInputs: [
      { name: 'IN', label: 'IN' },
      { name: 'S', label: 'S' },
    ],
    defaultOutputs: [
      { name: 'Y0', label: 'Y0' },
      { name: 'Y1', label: 'Y1' },
    ],
  },
  SR_LATCH: {
    type: 'SR_LATCH',
    name: 'SR Latch',
    category: 'sequential',
    description: 'Bistable multivibrator with Set and Reset inputs.',
    width: 100,
    height: 70,
    defaultInputs: [
      { name: 'S', label: 'S' },
      { name: 'R', label: 'R' },
    ],
    defaultOutputs: [
      { name: 'Q', label: 'Q' },
      { name: 'QBAR', label: 'Q̄' },
    ],
  },
  D_FLIP_FLOP: {
    type: 'D_FLIP_FLOP',
    name: 'D Flip-Flop',
    category: 'sequential',
    description: 'Captures data D on rising clock edge and stores value in Q.',
    width: 100,
    height: 80,
    defaultInputs: [
      { name: 'D', label: 'D' },
      { name: 'CLK', label: 'CLK' },
    ],
    defaultOutputs: [
      { name: 'Q', label: 'Q' },
      { name: 'QBAR', label: 'Q̄' },
    ],
  },
  JK_FLIP_FLOP: {
    type: 'JK_FLIP_FLOP',
    name: 'JK Flip-Flop',
    category: 'sequential',
    description: 'Universal flip-flop: Set (J=1), Reset (K=1), Toggle (J=K=1).',
    width: 100,
    height: 90,
    defaultInputs: [
      { name: 'J', label: 'J' },
      { name: 'CLK', label: 'CLK' },
      { name: 'K', label: 'K' },
    ],
    defaultOutputs: [
      { name: 'Q', label: 'Q' },
      { name: 'QBAR', label: 'Q̄' },
    ],
  },
  T_FLIP_FLOP: {
    type: 'T_FLIP_FLOP',
    name: 'T Flip-Flop',
    category: 'sequential',
    description: 'Toggles output state on each clock edge when T=1.',
    width: 100,
    height: 80,
    defaultInputs: [
      { name: 'T', label: 'T' },
      { name: 'CLK', label: 'CLK' },
    ],
    defaultOutputs: [
      { name: 'Q', label: 'Q' },
      { name: 'QBAR', label: 'Q̄' },
    ],
  },
  COUNTER_4BIT: {
    type: 'COUNTER_4BIT',
    name: '4-Bit Binary Counter',
    category: 'sequential',
    description: 'Synchronous 4-bit binary counter with Clock and Reset.',
    width: 110,
    height: 110,
    defaultInputs: [
      { name: 'CLK', label: 'CLK' },
      { name: 'RST', label: 'RST' },
    ],
    defaultOutputs: [
      { name: 'Q0', label: 'Q0' },
      { name: 'Q1', label: 'Q1' },
      { name: 'Q2', label: 'Q2' },
      { name: 'Q3', label: 'Q3' },
    ],
  },
  NMOS_TRANSISTOR: {
    type: 'NMOS_TRANSISTOR',
    name: 'NMOS Transistor (N-FET)',
    category: 'transistors',
    description: 'Turns ON (conducts drain to source) when Gate is HIGH (5V). When Gate is 0V, it is OFF (High-Z).',
    width: 80,
    height: 70,
    defaultInputs: [
      { name: 'G', label: 'Gate' },
      { name: 'D', label: 'Drain' },
    ],
    defaultOutputs: [{ name: 'S', label: 'Source' }],
    hasTransistorView: true,
  },
  PMOS_TRANSISTOR: {
    type: 'PMOS_TRANSISTOR',
    name: 'PMOS Transistor (P-FET)',
    category: 'transistors',
    description: 'Turns ON (conducts source to drain) when Gate is LOW (0V). When Gate is 5V, it is OFF (High-Z).',
    width: 80,
    height: 70,
    defaultInputs: [
      { name: 'G', label: 'Gate' },
      { name: 'S', label: 'Source' },
    ],
    defaultOutputs: [{ name: 'D', label: 'Drain' }],
    hasTransistorView: true,
  },
  PULLUP_RESISTOR: {
    type: 'PULLUP_RESISTOR',
    name: 'Pull-Up Resistor (+5V)',
    category: 'transistors',
    description: 'Pulls the line gently to +5V (Logic 1) when not pulled down to GND.',
    width: 70,
    height: 50,
    defaultInputs: [{ name: 'IN', label: 'Node' }],
    defaultOutputs: [{ name: 'OUT', label: '+5V' }],
  },
  PULLDOWN_RESISTOR: {
    type: 'PULLDOWN_RESISTOR',
    name: 'Pull-Down Resistor (GND)',
    category: 'transistors',
    description: 'Pulls the line to 0V (Logic 0) when not actively driven to +5V.',
    width: 70,
    height: 50,
    defaultInputs: [{ name: 'IN', label: 'Node' }],
    defaultOutputs: [{ name: 'OUT', label: '0V' }],
  },
};

/**
 * Helper to generate pins with accurate relative coordinates
 */
export function createComponentPins(
  type: GateType,
  width: number,
  height: number,
  componentId: string
) {
  const def = COMPONENT_DEFINITIONS[type];
  const inputs = def.defaultInputs.map((inp, idx) => {
    const spacing = height / (def.defaultInputs.length + 1);
    const y = spacing * (idx + 1);
    return {
      id: `${componentId}_in_${idx}`,
      name: inp.name,
      type: 'input' as const,
      index: idx,
      value: 'Z' as const,
      voltage: 0,
      relativeX: 0,
      relativeY: y,
    };
  });

  const outputs = def.defaultOutputs.map((out, idx) => {
    const spacing = height / (def.defaultOutputs.length + 1);
    const y = spacing * (idx + 1);
    return {
      id: `${componentId}_out_${idx}`,
      name: out.name,
      type: 'output' as const,
      index: idx,
      value: 0 as const,
      voltage: 0,
      relativeX: width,
      relativeY: y,
    };
  });

  return { inputs, outputs };
}
